version: '3.8'

services:
  r-shiny:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3838:3838"
    environment:
      - SHINY_LOG_LEVEL=INFO
      - R_LIBS_USER=/app/renv/library
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3838/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge

volumes:
  r-data:
    driver: local
  r-logs:
    driver: local