[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_NO_GUNICORN = "1"
NIXPACKS_INSTALL_CMD = "python -m venv .venv && .venv/bin/pip install -r requirements.txt"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = []