[phases.install]
# This command overrides the default install step.
# It installs build tools first, which is required by some dependencies.
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[start]
# This command starts the application.
cmd = "uvicorn main_app.main:app --host 0.0.0.0 --port $PORT" 