[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_NO_GUNICORN = "1"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -m pip install uvicorn[standard]"]