[build]
builder = "DOCKERFILE"
dockerfilePath = "main_app/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "monitor-legislativo-api"
build.builder = "DOCKERFILE"
build.dockerfilePath = "main_app/Dockerfile"
deploy.healthcheckPath = "/health"

[[services]]
name = "monitor-legislativo-rshiny"
build.builder = "DOCKERFILE"
build.dockerfilePath = "r-shiny-app/Dockerfile.simple"
deploy.healthcheckPath = "/"
source = "r-shiny-app/"