# Loki Configuration for Monitor Legislativo v4
# Phase 4 Week 15: Log aggregation and analysis
# Centralized logging for all application components

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  log_format: json

# Common configuration shared between components
common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Query limits and timeouts
limits_config:
  # Query limits
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 1 week
  max_cache_freshness_per_query: 10m
  
  # Ingestion limits
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  max_line_size: 256000
  max_line_size_truncate: false
  
  # Query performance
  max_query_parallelism: 32
  max_query_series: 10000
  max_query_lookback: 720h  # 30 days
  max_entries_limit_per_query: 5000
  max_streams_per_user: 10000
  
  # Per-tenant limits for Monitor Legislativo components
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  
  # Retention
  retention_period: 744h  # 31 days
  retention_stream:
    - selector: '{component="nginx"}'
      priority: 1
      period: 168h  # 7 days for nginx logs
    - selector: '{severity="error"}'
      priority: 2
      period: 2160h  # 90 days for error logs
    - selector: '{component="database"}'
      priority: 3
      period: 720h  # 30 days for database logs

# Schema configuration
schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: monitor_legislativo_index_
        period: 24h

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 0s

# Table manager (for chunk management)
table_manager:
  retention_deletes_enabled: true
  retention_period: 744h  # 31 days

# Ruler for alerting rules
ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  
  # Alert evaluation
  evaluation_interval: 1m
  poll_interval: 1m
  
  # External labels for alerts
  external_labels:
    cluster: monitor-legislativo-v4
    environment: production

# Analytics configuration
analytics:
  reporting_enabled: false

# Query frontend for improved performance
frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true
  downstream_url: http://127.0.0.1:3100
  log_queries_longer_than: 5s

# Query scheduler for load balancing
query_scheduler:
  max_outstanding_requests_per_tenant: 256

# Ingester configuration
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1048576  # 1MB
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /tmp/loki/wal
    checkpoint_duration: 5m
    flush_on_shutdown: true

# Compactor for chunk management
compactor:
  working_directory: /tmp/loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_cancel_period: 24h

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

# Index gateway (for better query performance)
index_gateway:
  mode: ring

# Query range configuration
query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        host: memcached:11211
        service: memcached

# Memberlist configuration for clustering
memberlist:
  node_name: loki-1
  randomize_node_name: false
  stream_timeout: 10s
  retransmit_factor: 4
  join_members:
    - loki:7946