# CITATION EXPORT SYSTEM - CIT-003
# =================================
# Export Brazilian legislative citations in multiple formats
# Supports: BibTeX, RIS, EndNote XML, Zotero, Plain Text
# 
# Features:
# - BibTeX format for LaTeX users
# - RIS format for reference managers (Zotero, Mendeley)
# - EndNote XML format for EndNote users
# - Plain text format with proper formatting
# - Bulk export capabilities
# - Memory-efficient processing for large document sets

cat("Loading Citation Export System...\n")

# Required packages for export functionality
export_packages <- c("xml2", "jsonlite")
missing_export_packages <- c()

for (pkg in export_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    missing_export_packages <- c(missing_export_packages, pkg)
  }
}

if (length(missing_export_packages) > 0) {
  cat("⚠️ Optional packages not available:", paste(missing_export_packages, collapse = ", "), "\n")
  cat("💡 Install with: install.packages(c(", paste0("'", missing_export_packages, "'", collapse = ", "), "))\n")
  cat("📄 Some export formats may have limited functionality\n")
}

# BIBTEX EXPORT FUNCTIONS
# =======================

#' Export to BibTeX Format
#' @param parsed_metadata_list List of parsed metadata objects
#' @param filename Output filename (optional)
#' @return BibTeX formatted string
export_bibtex <- function(parsed_metadata_list, filename = NULL) {
  if (!is.list(parsed_metadata_list)) {
    parsed_metadata_list <- list(parsed_metadata_list)
  }
  
  bibtex_entries <- c()
  
  for (i in seq_along(parsed_metadata_list)) {
    metadata <- parsed_metadata_list[[i]]
    bibtex_entry <- generate_bibtex_entry(metadata, i)
    bibtex_entries <- c(bibtex_entries, bibtex_entry)
  }
  
  # Add BibTeX header comment
  bibtex_content <- c(
    "% BibTeX entries for Brazilian Legislative Documents",
    "% Generated by Monitor Legislativo Citation System",
    paste("% Generated on:", Sys.time()),
    "",
    bibtex_entries
  )
  
  bibtex_text <- paste(bibtex_content, collapse = "\n")
  
  # Save to file if filename provided
  if (!is.null(filename)) {
    writeLines(bibtex_text, filename, useBytes = TRUE)
    cat("✅ BibTeX exported to:", filename, "\n")
  }
  
  return(bibtex_text)
}

#' Generate Single BibTeX Entry
#' @param metadata Parsed metadata object
#' @param index Entry index for citation key
#' @return BibTeX entry string
generate_bibtex_entry <- function(metadata, index) {
  if (is.null(metadata)) return("")
  
  # Generate citation key
  citation_key <- generate_bibtex_key(metadata, index)
  
  # Determine entry type
  entry_type <- determine_bibtex_entry_type(metadata)
  
  # Build BibTeX entry
  entry_lines <- c(
    paste0("@", entry_type, "{", citation_key, ",")
  )
  
  # Add required fields
  if (!isTRUE(is.null(metadata$original_title)) && metadata$original_title != "") {
    title_clean <- escape_bibtex_special_chars(metadata$original_title)
    entry_lines <- c(entry_lines, paste0("  title = {", title_clean, "},"))
  }
  
  if (!isTRUE(is.null(metadata$authority)) && metadata$authority != "") {
    author_clean <- escape_bibtex_special_chars(metadata$authority)
    entry_lines <- c(entry_lines, paste0("  author = {", author_clean, "},"))
  }
  
  if (!isTRUE(is.null(metadata$year)) && metadata$year != "") {
    entry_lines <- c(entry_lines, paste0("  year = {", metadata$year, "},"))
  }
  
  # Add document type
  if (!isTRUE(is.null(metadata$document_type)) && metadata$document_type != "") {
    type_clean <- escape_bibtex_special_chars(metadata$document_type)
    entry_lines <- c(entry_lines, paste0("  type = {", type_clean, "},"))
  }
  
  # Add document number
  if (!isTRUE(is.null(metadata$document_number)) && metadata$document_number != "") {
    entry_lines <- c(entry_lines, paste0("  number = {", metadata$document_number, "},"))
  }
  
  # Add jurisdiction
  if (!isTRUE(is.null(metadata$jurisdiction)) && metadata$jurisdiction != "") {
    entry_lines <- c(entry_lines, paste0("  address = {", metadata$jurisdiction, "},"))
  }
  
  # Add URL
  if (!isTRUE(is.null(metadata$url)) && metadata$url != "") {
    entry_lines <- c(entry_lines, paste0("  url = {", metadata$url, "},"))
  }
  
  # Add URN
  if (!isTRUE(is.null(metadata$urn)) && metadata$urn != "") {
    entry_lines <- c(entry_lines, paste0("  note = {URN: ", metadata$urn, "},"))
  }
  
  # Add access date
  entry_lines <- c(entry_lines, paste0("  urldate = {", format(Sys.Date(), "%Y-%m-%d"), "}"))
  
  # Close entry (remove last comma and add closing brace)
  if (length(entry_lines) > 1) {
    last_line <- entry_lines[length(entry_lines)]
    entry_lines[length(entry_lines)] <- stringr::str_remove(last_line, ",$")
  }
  entry_lines <- c(entry_lines, "}")
  
  return(paste(entry_lines, collapse = "\n"))
}

#' Generate BibTeX Citation Key
#' @param metadata Parsed metadata
#' @param index Entry index
#' @return Citation key string
generate_bibtex_key <- function(metadata, index) {
  key_parts <- c()
  
  # Use authority abbreviation
  if (!isTRUE(is.null(metadata$authority)) && metadata$authority != "") {
    if (grepl("BRASIL", metadata$authority)) {
      key_parts <- c(key_parts, "brasil")
    } else if (grepl("ESTADO", metadata$authority)) {
      key_parts <- c(key_parts, "estado")
    } else if (grepl("MUNICÍPIO", metadata$authority)) {
      key_parts <- c(key_parts, "municipio")
    } else {
      # Use first word of authority
      auth_word <- stringr::str_extract(tolower(metadata$authority), "^\\w+")
      key_parts <- c(key_parts, auth_word)
    }
  }
  
  # Add year
  if (!isTRUE(is.null(metadata$year)) && metadata$year != "") {
    key_parts <- c(key_parts, metadata$year)
  }
  
  # Add document number if available
  if (!isTRUE(is.null(metadata$document_number)) && metadata$document_number != "") {
    # Clean number for use in key
    number_clean <- stringr::str_remove_all(metadata$document_number, "[^\\d]")
    if (number_clean != "" && nchar(number_clean) <= 6) {
      key_parts <- c(key_parts, paste0("n", number_clean))
    }
  }
  
  # Fallback to index if no other parts
  if (length(key_parts) == 0) {
    key_parts <- c("doc", sprintf("%03d", index))
  }
  
  return(paste(key_parts, collapse = "_"))
}

#' Determine BibTeX Entry Type
#' @param metadata Parsed metadata
#' @return BibTeX entry type
determine_bibtex_entry_type <- function(metadata) {
  if (is.null(metadata$document_type)) return("misc")
  
  doc_type <- tolower(metadata$document_type)
  
  if (grepl("lei|law", doc_type)) return("legislation")
  if (grepl("decreto|decree", doc_type)) return("legislation") 
  if (grepl("constituição|constitution", doc_type)) return("legislation")
  if (grepl("resolução|resolution", doc_type)) return("techreport")
  if (grepl("portaria|ordinance", doc_type)) return("techreport")
  if (grepl("instrução|instruction", doc_type)) return("techreport")
  
  return("misc")
}

#' Escape BibTeX Special Characters
#' @param text Text to escape
#' @return Escaped text
escape_bibtex_special_chars <- function(text) {
  if (isTRUE(is.null(text)) || text == "") return("")
  
  # Escape BibTeX special characters
  text <- gsub("\\\\", "\\\\textbackslash{}", text)  # Backslash first
  text <- gsub("\\{", "\\\\{", text)
  text <- gsub("\\}", "\\\\}", text)
  text <- gsub("\\$", "\\\\$", text)
  text <- gsub("&", "\\\\&", text)
  text <- gsub("%", "\\\\%", text)
  text <- gsub("#", "\\\\#", text)
  text <- gsub("\\^", "\\\\textasciicircum{}", text)
  text <- gsub("_", "\\\\_", text)
  text <- gsub("~", "\\\\textasciitilde{}", text)
  
  return(text)
}

# RIS EXPORT FUNCTIONS
# ===================

#' Export to RIS Format
#' @param parsed_metadata_list List of parsed metadata objects
#' @param filename Output filename (optional)
#' @return RIS formatted string
export_ris <- function(parsed_metadata_list, filename = NULL) {
  if (!is.list(parsed_metadata_list)) {
    parsed_metadata_list <- list(parsed_metadata_list)
  }
  
  ris_entries <- c()
  
  for (i in seq_along(parsed_metadata_list)) {
    metadata <- parsed_metadata_list[[i]]
    ris_entry <- generate_ris_entry(metadata)
    ris_entries <- c(ris_entries, ris_entry, "")  # Add empty line between entries
  }
  
  ris_text <- paste(ris_entries, collapse = "\n")
  
  # Save to file if filename provided
  if (!is.null(filename)) {
    writeLines(ris_text, filename, useBytes = TRUE)
    cat("✅ RIS exported to:", filename, "\n")
  }
  
  return(ris_text)
}

#' Generate Single RIS Entry
#' @param metadata Parsed metadata object
#' @return RIS entry string
generate_ris_entry <- function(metadata) {
  if (is.null(metadata)) return("")
  
  # Determine RIS type
  ris_type <- determine_ris_type(metadata)
  
  ris_lines <- c(
    paste0("TY  - ", ris_type)  # Type of reference
  )
  
  # Add title
  if (!isTRUE(is.null(metadata$original_title)) && metadata$original_title != "") {
    ris_lines <- c(ris_lines, paste0("TI  - ", metadata$original_title))
  }
  
  # Add author/authority
  if (!isTRUE(is.null(metadata$authority)) && metadata$authority != "") {
    ris_lines <- c(ris_lines, paste0("AU  - ", metadata$authority))
  }
  
  # Add publication year
  if (!isTRUE(is.null(metadata$year)) && metadata$year != "") {
    ris_lines <- c(ris_lines, paste0("PY  - ", metadata$year))
  }
  
  # Add publication date
  if (!isTRUE(is.null(metadata$publication_date)) && metadata$publication_date != "") {
    ris_lines <- c(ris_lines, paste0("DA  - ", metadata$publication_date))
  }
  
  # Add document type as note
  if (!isTRUE(is.null(metadata$document_type)) && metadata$document_type != "") {
    ris_lines <- c(ris_lines, paste0("N1  - ", metadata$document_type))
  }
  
  # Add document number
  if (!isTRUE(is.null(metadata$document_number)) && metadata$document_number != "") {
    ris_lines <- c(ris_lines, paste0("VL  - ", metadata$document_number))
  }
  
  # Add jurisdiction as publisher
  if (!isTRUE(is.null(metadata$jurisdiction)) && metadata$jurisdiction != "") {
    ris_lines <- c(ris_lines, paste0("PB  - ", metadata$jurisdiction))
  }
  
  # Add URL
  if (!isTRUE(is.null(metadata$url)) && metadata$url != "") {
    ris_lines <- c(ris_lines, paste0("UR  - ", metadata$url))
  }
  
  # Add URN as note
  if (!isTRUE(is.null(metadata$urn)) && metadata$urn != "") {
    ris_lines <- c(ris_lines, paste0("N1  - URN: ", metadata$urn))
  }
  
  # End of record
  ris_lines <- c(ris_lines, "ER  - ")
  
  return(paste(ris_lines, collapse = "\n"))
}

#' Determine RIS Type
#' @param metadata Parsed metadata
#' @return RIS type code
determine_ris_type <- function(metadata) {
  if (is.null(metadata$document_type)) return("GEN")  # Generic
  
  doc_type <- tolower(metadata$document_type)
  
  if (grepl("lei|law|decreto|decree|constituição|constitution", doc_type)) return("BILL")
  if (grepl("resolução|resolution|portaria|ordinance", doc_type)) return("RPRT")  # Report
  if (grepl("instrução|instruction", doc_type)) return("RPRT")
  
  return("GEN")  # Generic fallback
}

# ENDNOTE XML EXPORT FUNCTIONS
# ============================

#' Export to EndNote XML Format
#' @param parsed_metadata_list List of parsed metadata objects
#' @param filename Output filename (optional)
#' @return EndNote XML string
export_endnote_xml <- function(parsed_metadata_list, filename = NULL) {
  if (!requireNamespace("xml2", quietly = TRUE)) {
    cat("⚠️ xml2 package required for EndNote XML export\n")
    return(NULL)
  }
  
  if (!is.list(parsed_metadata_list)) {
    parsed_metadata_list <- list(parsed_metadata_list)
  }
  
  # Create XML structure
  xml_doc <- xml2::xml_new_root("xml")
  records_node <- xml2::xml_add_child(xml_doc, "records")
  
  for (i in seq_along(parsed_metadata_list)) {
    metadata <- parsed_metadata_list[[i]]
    record_node <- generate_endnote_record(records_node, metadata, i)
  }
  
  xml_text <- as.character(xml_doc)
  
  # Save to file if filename provided
  if (!is.null(filename)) {
    xml2::write_xml(xml_doc, filename)
    cat("✅ EndNote XML exported to:", filename, "\n")
  }
  
  return(xml_text)
}

#' Generate EndNote XML Record
#' @param parent_node Parent XML node
#' @param metadata Parsed metadata object
#' @param index Record index
#' @return XML record node
generate_endnote_record <- function(parent_node, metadata, index) {
  if (!requireNamespace("xml2", quietly = TRUE)) return(NULL)
  
  record_node <- xml2::xml_add_child(parent_node, "record")
  
  # Add database info
  database_node <- xml2::xml_add_child(record_node, "database", 
                                      name = "Monitor Legislativo", 
                                      path = "monitor_legislativo.enl")
  
  # Add source info
  source_app_node <- xml2::xml_add_child(record_node, "source-app", 
                                        name = "Monitor Legislativo Citation System",
                                        version = "1.0")
  
  # Add record number
  rec_number_node <- xml2::xml_add_child(record_node, "rec-number", as.character(index))
  
  # Add reference type (Bill/Law for legislation)
  ref_type_node <- xml2::xml_add_child(record_node, "ref-type", name = "Bill")
  
  # Add contributors (authors/authorities)
  contributors_node <- xml2::xml_add_child(record_node, "contributors")
  authors_node <- xml2::xml_add_child(contributors_node, "authors")
  
  if (!isTRUE(is.null(metadata$authority)) && metadata$authority != "") {
    author_node <- xml2::xml_add_child(authors_node, "author")
    xml2::xml_add_child(author_node, "style", face = "normal", font = "default", size = "100%", 
                       metadata$authority)
  }
  
  # Add titles
  titles_node <- xml2::xml_add_child(record_node, "titles")
  
  if (!isTRUE(is.null(metadata$original_title)) && metadata$original_title != "") {
    title_node <- xml2::xml_add_child(titles_node, "title")
    xml2::xml_add_child(title_node, "style", face = "normal", font = "default", size = "100%",
                       metadata$original_title)
  }
  
  # Add dates
  dates_node <- xml2::xml_add_child(record_node, "dates")
  if (!isTRUE(is.null(metadata$year)) && metadata$year != "") {
    year_node <- xml2::xml_add_child(dates_node, "year")
    xml2::xml_add_child(year_node, "style", face = "normal", font = "default", size = "100%",
                       metadata$year)
  }
  
  # Add publisher (jurisdiction)
  publisher_node <- xml2::xml_add_child(record_node, "publisher")
  if (!isTRUE(is.null(metadata$jurisdiction)) && metadata$jurisdiction != "") {
    xml2::xml_add_child(publisher_node, "style", face = "normal", font = "default", size = "100%",
                       metadata$jurisdiction)
  }
  
  # Add URLs
  urls_node <- xml2::xml_add_child(record_node, "urls")
  if (!isTRUE(is.null(metadata$url)) && metadata$url != "") {
    related_urls_node <- xml2::xml_add_child(urls_node, "related-urls")
    url_node <- xml2::xml_add_child(related_urls_node, "url")
    xml2::xml_add_child(url_node, "style", face = "normal", font = "default", size = "100%",
                       metadata$url)
  }
  
  # Add custom fields
  custom_node <- xml2::xml_add_child(record_node, "custom7")  # Document type
  if (!isTRUE(is.null(metadata$document_type)) && metadata$document_type != "") {
    xml2::xml_add_child(custom_node, "style", face = "normal", font = "default", size = "100%",
                       metadata$document_type)
  }
  
  return(record_node)
}

# PLAIN TEXT EXPORT FUNCTIONS
# ===========================

#' Export to Plain Text Format
#' @param parsed_metadata_list List of parsed metadata objects
#' @param format Citation format ("abnt", "apa", "vancouver", "bluebook")
#' @param language Language for citations
#' @param filename Output filename (optional)
#' @return Plain text citations
export_plain_text <- function(parsed_metadata_list, format = "abnt", language = "pt", filename = NULL) {
  if (!is.list(parsed_metadata_list)) {
    parsed_metadata_list <- list(parsed_metadata_list)
  }
  
  # Load citation templates if not available
  if (!exists("format_abnt_citation")) {
    if (file.exists("modules/citations/citation_templates.R")) {
      source("modules/citations/citation_templates.R")
    }
  }
  
  citations <- c()
  
  # Add header
  if (format == "abnt") {
    if (language == "pt") {
      citations <- c(citations, "REFERÊNCIAS", "")
    } else {
      citations <- c(citations, "REFERENCES", "")
    }
  } else {
    citations <- c(citations, paste("CITATIONS -", toupper(format)), "")
  }
  
  # Generate citations
  for (i in seq_along(parsed_metadata_list)) {
    metadata <- parsed_metadata_list[[i]]
    
    if (exists(paste0("format_", format, "_citation"))) {
      citation_func <- get(paste0("format_", format, "_citation"))
      
      if (format == "vancouver") {
        citation <- citation_func(metadata, i)
      } else {
        citation <- citation_func(metadata, language)
      }
    } else {
      citation <- paste("Unsupported format:", format)
    }
    
    citations <- c(citations, citation, "")
  }
  
  plain_text <- paste(citations, collapse = "\n")
  
  # Save to file if filename provided
  if (!is.null(filename)) {
    writeLines(plain_text, filename, useBytes = TRUE)
    cat("✅ Plain text exported to:", filename, "\n")
  }
  
  return(plain_text)
}

# BULK EXPORT FUNCTIONS
# =====================

#' Export Multiple Formats Simultaneously
#' @param parsed_metadata_list List of parsed metadata objects
#' @param output_dir Output directory
#' @param base_filename Base filename (without extension)
#' @param formats Vector of formats to export
#' @return List of export results
bulk_export_citations <- function(parsed_metadata_list, 
                                 output_dir = "exports", 
                                 base_filename = "brazilian_legislative_citations",
                                 formats = c("bibtex", "ris", "endnote", "abnt_plain", "apa_plain")) {
  
  # Create output directory if it doesn't exist
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
    cat("📁 Created output directory:", output_dir, "\n")
  }
  
  export_results <- list()
  
  for (format in formats) {
    tryCatch({
      if (format == "bibtex") {
        filename <- file.path(output_dir, paste0(base_filename, ".bib"))
        result <- export_bibtex(parsed_metadata_list, filename)
        export_results[[format]] <- list(success = TRUE, file = filename, content = result)
        
      } else if (format == "ris") {
        filename <- file.path(output_dir, paste0(base_filename, ".ris"))
        result <- export_ris(parsed_metadata_list, filename)
        export_results[[format]] <- list(success = TRUE, file = filename, content = result)
        
      } else if (format == "endnote") {
        filename <- file.path(output_dir, paste0(base_filename, ".xml"))
        result <- export_endnote_xml(parsed_metadata_list, filename)
        export_results[[format]] <- list(success = TRUE, file = filename, content = result)
        
      } else if (format == "abnt_plain") {
        filename <- file.path(output_dir, paste0(base_filename, "_abnt.txt"))
        result <- export_plain_text(parsed_metadata_list, "abnt", "pt", filename)
        export_results[[format]] <- list(success = TRUE, file = filename, content = result)
        
      } else if (format == "apa_plain") {
        filename <- file.path(output_dir, paste0(base_filename, "_apa.txt"))
        result <- export_plain_text(parsed_metadata_list, "apa", "en", filename)
        export_results[[format]] <- list(success = TRUE, file = filename, content = result)
        
      } else {
        export_results[[format]] <- list(success = FALSE, error = paste("Unsupported format:", format))
      }
      
    }, error = function(e) {
      export_results[[format]] <- list(success = FALSE, error = e$message)
      cat("❌ Export failed for", format, ":", e$message, "\n")
    })
  }
  
  # Summary
  successful_exports <- sum(sapply(export_results, function(x) x$success))
  cat("✅ Bulk export completed:", successful_exports, "of", length(formats), "formats exported\n")
  
  return(export_results)
}

#' Test Citation Export System
#' @return Test results
test_citation_export <- function() {
  cat("Testing Citation Export System...\n")
  
  # Load dependencies if not available
  if (!exists("parse_brazilian_legislative_metadata")) {
    if (file.exists("modules/citations/brazilian_legislative_parser.R")) {
      source("modules/citations/brazilian_legislative_parser.R")
    }
  }
  
  if (!exists("format_abnt_citation")) {
    if (file.exists("modules/citations/citation_templates.R")) {
      source("modules/citations/citation_templates.R")
    }
  }
  
  # Test documents
  test_docs <- data.frame(
    title = c(
      "Lei Federal nº 14.133/2021 - Nova Lei de Licitações",
      "Resolução ANTT nº 5.232/2020 - RNTRC"
    ),
    state = c("DF", "DF"),
    date = c("2021-04-01", "2020-12-10"),
    url = c("http://example1.com", "http://example2.com"),
    urn = c("", ""),
    stringsAsFactors = FALSE
  )
  
  if (exists("parse_brazilian_legislative_metadata")) {
    # Parse metadata
    parsed_list <- parse_brazilian_legislative_metadata(test_docs)
    
    # Test BibTeX export
    bibtex_result <- export_bibtex(parsed_list)
    cat("\n--- BibTeX Sample ---\n")
    cat(substr(bibtex_result, 1, 200), "...\n")
    
    # Test RIS export
    ris_result <- export_ris(parsed_list)
    cat("\n--- RIS Sample ---\n")
    cat(substr(ris_result, 1, 200), "...\n")
    
    # Test Plain Text export
    plain_result <- export_plain_text(parsed_list, "abnt", "pt")
    cat("\n--- ABNT Plain Text Sample ---\n")
    cat(substr(plain_result, 1, 300), "...\n")
    
    return(list(
      bibtex = bibtex_result,
      ris = ris_result,
      plain_text = plain_result
    ))
  } else {
    cat("⚠️ Parser not available for testing\n")
    return(NULL)
  }
}

cat("✅ Citation Export System loaded successfully\n")
cat("   📄 BibTeX export: ENABLED\n")
cat("   📊 RIS export: ENABLED\n")
cat("   📋 EndNote XML export: ENABLED\n")
cat("   📝 Plain text export: ENABLED\n")
cat("   📦 Bulk export: ENABLED\n")
cat("   💾 File output: SUPPORTED\n")

# Export main functions
CITATION_EXPORT_FUNCTIONS <- list(
  export_bibtex = export_bibtex,
  export_ris = export_ris,
  export_endnote_xml = export_endnote_xml,
  export_plain_text = export_plain_text,
  bulk_export_citations = bulk_export_citations,
  test_citation_export = test_citation_export
)